provider "aws" {
  region = var.region
}

module "service" {
  source                             = "git::https://gitlab.com/inf-code/service.git?ref=tags/v1.4.0"
  region                             = var.region
  namespace                          = var.namespace
  stage                              = var.stage
  name                               = var.name
  attributes                         = var.attributes
  delimiter                          = var.delimiter
  tags                               = var.tags
  target_group_port                  = var.target_group_port
  target_group_protocol              = var.target_group_protocol
  target_group_target_type           = var.target_group_target_type
  health_check_path                  = var.health_check_path
  health_check_timeout               = var.health_check_timeout
  health_check_healthy_threshold     = var.health_check_healthy_threshold
  health_check_unhealthy_threshold   = var.health_check_healthy_threshold
  health_check_interval              = var.health_check_interval
  health_check_matcher               = var.health_check_matcher
  load_balancer_listener_arn         = var.load_balancer_listener_arn
  load_balancer_listener_paths       = var.load_balancer_listener_paths
  container_image                    = var.container_image
  container_memory                   = var.container_memory
  container_memory_reservation       = var.container_memory_reservation
  container_port_mappings            = var.container_port_mappings
  container_port                     = var.container_port
  container_cpu                      = var.container_cpu
  container_essential                = var.container_essential
  container_environment              = var.container_environment
  container_secrets                  = var.container_secrets
  container_readonly_root_filesystem = var.container_readonly_root_filesystem
  vpc_default_security_group_id      = var.vpc_default_security_group_id
  ecs_cluster_arn                    = var.ecs_cluster_arn
  ecs_launch_type                    = var.ecs_launch_type
  vpc_id                             = var.vpc_id
  private_subnet_ids                 = var.private_subnet_ids
  ignore_changes_task_definition     = var.ignore_changes_task_definition
  network_mode                       = var.network_mode
  assign_public_ip                   = var.assign_public_ip
  propagate_tags                     = var.propagate_tags
  deployment_minimum_healthy_percent = var.deployment_minimum_healthy_percent
  deployment_maximum_percent         = var.deployment_maximum_percent
  deployment_controller_type         = var.deployment_controller_type
  desired_count                      = var.desired_count
  task_memory                        = var.task_memory
  task_cpu                           = var.task_cpu
  task_role_policy                   = var.task_role_policy
  task_exec_role_policy              = var.task_exec_role_policy
  db_enabled                         = var.db_enabled
  db_port                            = var.db_port
  db_security_group_id               = var.db_security_group_id
  redis_enabled                      = var.redis_enabled
  redis_port                         = var.redis_port
  redis_security_group_id            = var.redis_security_group_id
}
